// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxsVSSPBDxmyt5WiO1NBv3bHWP_eXat3s',
    appId: '1:909006330680:web:835c03b7af2520e840ffcd',
    messagingSenderId: '909006330680',
    projectId: 'egycamp-b5e35',
    authDomain: 'egycamp-b5e35.firebaseapp.com',
    databaseURL: 'https://egycamp-b5e35-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'egycamp-b5e35.appspot.com',
    measurementId: 'G-J9482NEJLJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI4EZQUcdlHl5vIs3MJ8Gk2UZsCMMWPRY',
    appId: '1:909006330680:android:eab678edc51a8d4540ffcd',
    messagingSenderId: '909006330680',
    projectId: 'egycamp-b5e35',
    databaseURL: 'https://egycamp-b5e35-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'egycamp-b5e35.appspot.com',
  );
}
